GO_EASY_ON_ME = 1
ARCHS = arm64 arm64e

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = EntitlementFix_gamed
EntitlementFix_gamed_FILES = Tweak.xm
EntitlementFix_gamed_PRIVATEFRAMEWORKS = GameCenterFoundation

include $(THEOS_MAKE_PATH)/tweak.mk
